### ISSUE TITLE
Gecko/Golden Gecko(in random encounters) has Radscorpion tails in their inventory.

### ISSUE THREAD

**Issue by Dumbisted** [dekrus/Fallout2MechanicsMiniRework#1]
I know those tails are supposed to let Gecko deal poison damage on their attack, but _they never use it_.

Maybe Gecko's "melee weapon" is not registered as poisonable weapon, I guess.

---

Version: 1.98

**Comment by dekrus** [comment]
Hello!
How many tails does a single gecko have?
What is a living gecko called when examined with a cursor?

In my mod, tails are added exclusively to creatures with a knife or spear in their hands/inventory. I was unable to replicate this bug in my version of RPU v28 combined with Ecco 0.9.3.

Could you provide a save file featuring live geckos, where scorpion tails can be found post-mortem?

**Comment by Dumbisted** [comment]
Hmm, this is strange. I'm keep looking for the bug to be reproduced since I've upgraded the mod to 1.98.1v, but it's not happening in where I remember.

As I remember, they had 3 of tails in their inventory but can't remember how they were displayed upon examined- sorry.


But I found another bug that Geckos are using an Antidote. The version is 1.98.1v.

![scr00011](https://github.com/dekrus/Fallout2MechanicsMiniRework/assets/52318642/456bc0fb-a356-44d4-94ec-5c50cd60ae0f)
![scr00012](https://github.com/dekrus/Fallout2MechanicsMiniRework/assets/52318642/ccdb2675-8b67-407d-91d3-415f6ede30f3)

**Comment by dekrus** [comment]
This is my mistake, I will fix this bug in the next release.
Only bipedal creatures (humans) can use items. 
But it turned out that in the game, geckos and plants are also considered bipedal (humans), and all other non-humans (even Deathclaws, Wanamingos and Floaters) are quadrupeds.

**Comment by Dumbisted** [comment]
Guess it's solved then, appreciated for your efforts!
