### ISSUE TITLE
Player is randomly being disarmed in combat.

### ISSUE THREAD

**Issue by Dumbisted** [dekrus/Fallout2MechanicsMiniRework#2]
As the title, it happens at random time(rarely), only in combat.

If a player is disarmed by this bug, item in both of slots are moved into the player's inventory.

Here's a part of log from debug.log(when the bug occured) and sfall-log.ini:
[possiblebug2.txt](https://github.com/dekrus/Fallout2MechanicsMiniRework/files/15245932/possiblebug2.txt)
[sfall-log.txt](https://github.com/dekrus/Fallout2MechanicsMiniRework/files/15245934/sfall-log.txt)

---

F2MMR Version: 1.98v

Sfall Version: 4.4.3.1

Used mods:
1. RPU v28
2. Maps Updated
3. EcCo 0.9.3
4. Talking Heads Addon
5. Inventory Filter 2.0.3
6. ["Get a perk at each level" Script](https://www.nma-fallout.com/threads/get-a-perk-at-each-level.215408/#post-4288628)
7. Autoclosebox (in example_mods from modderspack)

**Comment by dekrus** [comment]
Hmm, very strange! In combat, a weapon can only end up on the ground. 
Weapons from the hands are added to the inventory only outside of combat, during an unsuccessful stealing, and then they are re-equiped.

Could you provide a save file from before the combat in which this occurred? 
Or at least more information: what weapon the player had, who initiated the attack and with what weapon, or if any pattern has been noticed?

**Comment by Dumbisted** [comment]
I've still had no clue how to reproduce the bug again, but it has just happened. But no luck of saving BEFORE combat, since it was a random encounter. So I'm only posting debug.log for this time. if you need the save file and some other things too, I'll post it.

[debug.log](https://github.com/dekrus/Fallout2MechanicsMiniRework/files/15368863/debug.log)
The combat starts from line 6080~.

I had encountered Patrols vs Slavers near Vault City area and a Patrol had first attack on one of the slavers. Then my Combat Knife in secondary slot was suddenly moved into my inventory as soon as the patrol's attack hitted on the slaver. unlike previous times, my Combat Shotgun was not effected by it and stayed in my primary slot.

**Comment by dekrus** [comment]
I made a fix for the most likely cause of this bug in version 1.98.2.
If it doesn’t happen again, then it was it :)

Thank you for the bug reports!

**Comment by Dumbisted** [comment]
I'll keep test it along with issue #3 - until find the same issue again, you can mark this issue as sloved and closed.

It's my word to say thank you, for the mod anyway :)
