### ISSUE TITLE
Gecko died from posion damage does not drop it's hide.

### ISSUE THREAD

**Issue by Dumbisted** [dekrus/Fallout2MechanicsMiniRework#4]
Ditto- and of course, I do have Gecko Skinning Perk!

I've found the bug from Golden Gecko for now; did not tested on other types.

----------------------------------------

F2MMR Version: 1.98.2v

Sfall Version: 4.4.3.1

Used mods:

1. RPU v29
2. Maps Updated
3. EcCo 0.9.5
4. Talking Heads Addon
5. Inventory Filter 2.0.3
6. ["Get a perk at each level" Script](https://www.nma-fallout.com/threads/get-a-perk-at-each-level.215408/#post-4288628)
7. Autoclosebox (in example_mods from modderspack)

**Comment by dekrus** [comment]
Yes, it turned out to be a consequence of the game's softlock fix...

The fix for this bug is ready.

**Comment by dekrus** [comment]
Thanks for posting bug reports! 
Testing is the most time-consuming and difficult part of modding :)

I advise you to download the new version of the .dat file from the releases page.
