### ISSUE TITLE
Healing Rate is increased and keep being fixed after used some chems.

### ISSUE THREAD

**Issue by Dumbisted** [dekrus/Fallout2MechanicsMiniRework#5]
With unknown reason.

I encountered Kaga and fought him. while in the combat, I was hurt bad so I used **Psycho first** then **Super Stimpack(it's a first time I'm using Super Stimpack in the save) right after that**(might be swapped; sorry, my memory is not that correct :/). After the combat ended, I passed a hour and the bug just happened. The increased healing rate is not decreasing no matter how much time passed.

I'm posting the save file just right BEFORE the bug happens, so you can reproduce the bug. Also included debug log and sfall-log: 
[SLOT03_2.zip](https://github.com/dekrus/Fallout2MechanicsMiniRework/files/15447355/SLOT03_2.zip)

----------------------------------------------------------------------------

F2MMR Version: 1.98.3v

Sfall Version: 4.4.3.1 + cnc-ddraw

Used mods:

1. RPU v29
2. Maps Updated
3. Fo2tweaks v12.17
4. EcCo v0.9.5
5. Talking Heads Addon
6. Inventory Filter 2.0.3
7. ["Get a perk at each level" Script](https://www.nma-fallout.com/threads/get-a-perk-at-each-level.215408/#post-4288628)
8. Autoclosebox (in example_mods from modderspack)

**Comment by dekrus** [comment]
Compatibility issue with EcCo 0.9.5, but easy to fix this time. 
There are 2 options depending on which mechanics of healing with stimpaks you want to choose:
- You can disable my healing mod by setting "RegenMod=0" in "F2MechanicsMiniRework.ini". 
- Alternatively, you can disable EcCo stimpak scaling by setting "healing_skill_max=0" in "misc.ini" (Fallout 2\\mods\\ecco folder). 

I'll add this information to the description on the main page. Thank you, as always, for the bug report!
