### ISSUE TITLE
Хакинг не работает.

### ISSUE THREAD

**Issue by UsaTerror** [dekrus/Fallout2MechanicsMiniRework#6]
critter_adjust_poison
critter_check_poison
insert_drug_effect
хакинг этих функции в sfall 5 НЕ РАБОТАЕТ!

**Comment by dekrus** [comment]
Да, уже заметил, что в процедурах связанными с крючками хаки не работают...
Поэтому вместо хака в "insert_drug_effect" используется "HOOK_DRUGSEFFECT". 
Для critter_check_poison не сильно страшно, что хак не работает, там просто дефолтное сообщение о снижении количества яда отключается.

А вот для critter_adjust_poison очень плохо что не работает! Но если не менять значение для передоза яда, то это будет не заметно. Пойду хотелку в иссуе оформлю :)

**Comment by dekrus** [comment]
В версии 1.99 для sfall 5.0.8+ использовал новые возможности "HOOK_ADJUSTPOISON"
